---
title: "Data Structures Exercises"
author: "Hicham Zmarrou"
date: "Notebook -- <http://bit.ly/2pHMYck>  <br /> <br />"
output:
  html_notebook:
    highlight: pygments
    number_sections: no
    theme: cosmo
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
subtitle: Introduction to R
venue: TNO data science courses
---


<hr>


__References__

Most of this material is borrowed from:

* Textbook: [R for Data Science: Import, Tidy, Transform, Visualize, and Model Data ](http://amzn.to/2r3x3ZF)

______________________________________________________________________________________________________________________________________


## Data management Exercises

**Exercise 1:** Select the first three columns of the iris dataset using their column names. HINT: Use `select()`.

**Exercise 2:** Select all the columns of the iris dataset except “Petal Width”. HINT: Use “-“.

**Exercise 3:** Select all columns of the iris dataset that start with the character string “P”.

**Exercise 4:** Filter the rows of the iris dataset for Sepal.Length >= 4.6 and Petal.Width >= 0.5.

**Exercise 5:** Pipe the iris data frame to the function that will select two columns (Sepal.Width and Sepal.Length). HINT: Use pipe operator `%>%`.

**Exercise 6:** Arrange rows by a particular column, such as the Sepal.Width. HINT: Use `arrange()`.

**Exercise 7:** Select three columns from iris, arrange the rows by Sepal.Length, then arrange the rows by Sepal.Width.

**Exercise 8:** Create a new column called proportion, which is the ratio of Sepal.Length to Sepal.Width. HINT: Use `mutate()`.

**Exercise 9:**  Compute the average number of Sepal.Length, apply the mean() function to the column Sepal.Length, and call the summary value “avg_slength”. HINT: Use `summarize()`.

**Exercise 10:** Split the iris data frame by the Sepal.Length, then ask for the same summary statistics as above. HINT: `Use group_by()`.

