#####################
## Exercise 0
#####################
Go to the following link and go through the tutorial reproducing the results.
 
http://www.datacarpentry.org/R-ecology-lesson/05-r-and-databases.html

#####################
## Exercise 1
#####################
Load libraries: dplyr, dbplyr, DBI, RSQLite, nycflights13 if they are yet loaded. 
Create a connection to temporal in-memory SQLite database (the database will be created on-the-fly so you do not have to take care of this).

#####################
## Exercise 2
#####################
Upload data sets nycflights13::flights and nycflights13::planes to the database as non temporal tables.

#####################
## Exercise 3
#####################
List names of columns in flights table (hint: There is a function in DBI package for this).

#####################
## Exercise 4
#####################
Use SQL query to count number of flights per carrier and pull it to a local tibble.



#####################
## Exercise 5
#####################
Do the same thing using dplyr verbs instead of SQL.

#####################
## Exercise 6
#####################
Calculate number of flights, mean and total distance per plane, discard records with NA at tailnum column and save it to temporal table.

#####################
## Exercise 7
#####################
List all the tables in the database (hint: There is a function in DBI package for this).


#####################
## Exercise 8
#####################
Use head(), tail() and nrow() to investigate table planes. Do you understand why the latter two do not work?

#####################
## Exercise 9
#####################
Join the table from exercise 6 with planes table and without pulling the data to local frame find manufacturers 
and models of 10 planes with the highest total flown distance.

 
#####################
## Exercise 10
#####################
Check what is the actual SQL query generated by the code you have created in exercise 9.


